<a href="https://colab.research.google.com/github/revivalroot/2026-BDA/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Numpy

In [1]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[9.66139624e-316, 0.00000000e+000, 6.60831929e-310],
       [1.92218462e+227, 7.10584583e+159, 5.50997443e-310]])

In [3]:
import numpy as np

a = np.ndarray((3, 2), dtype=int)
a

array([[           206927562,                    0],
       [   59702385373257755, -8639591816434879439],
       [ -781641917882640564,    16732479637715200]])

In [4]:
a = np.ndarray((3, 2), int)
a

array([[      206544363,               0],
       [       11707264, 133753316550512],
       [133753733533728, 133753853930736]])

## ndarray(다차원 배열)의 주요 속성

In [5]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [9]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [11]:
np.array([1, 'py', 3.14])


array(['1', 'py', '3.14'], dtype='<U32')

In [13]:
import numpy as np

unicode_array = np.array(['가나다', '라마바', '사아자'], dtype = '<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [14]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'], dtype = '<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

### 내장함수 arange()와 linspace()

In [16]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [17]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.5))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]


In [18]:
import numpy as np

a= np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# np.reshape(a, (3, 5)) -> error 원소 수 가 안맞음

In [20]:
np.linspace(2.0, 3.0) # num을 설정하지 않으면 default값이 50

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [21]:
np.linspace(2.0, 3.0, retstep=True) #마지막에 샘플 수 사이의 간격 반환

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [22]:
print( (3-2) / (50-1))

0.02040816326530612


In [23]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [24]:
print( (3-2) / 50)

0.02


In [25]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [26]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

### 내장함수 zeros()와 ones(), empty()

In [29]:
import numpy as np

a = np.zeros(5)
a


array([0., 0., 0., 0., 0.])

In [30]:
a.dtype

dtype('float64')

In [31]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [32]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [33]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [37]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [38]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [40]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [41]:
np.full([2,3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [42]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [43]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [44]:
np.empty(3)   # 값은 메모리 값 지정-> 원소 값은 예측할 수 없음

array([4.9e-324, 9.9e-324, 1.5e-323])

In [45]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [46]:
np.empty([2, 3], dtype=int)

array([[      259346479,               0, 133752881251952],
       [133752881265520, 133752896398192, 133752881255920]])

In [47]:
import numpy as np
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

### 배열 연산

In [51]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [52]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [53]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [55]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [57]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [58]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [60]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [74]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [75]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [76]:
a@b

array([[12,  6],
       [12,  6]])

In [77]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [78]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [80]:
import numpy as np
print(np.matmul(a, b))
print(np.matmul(b, a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [67]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [68]:
a.sum()

np.int64(46)

In [69]:
a.sum(axis=0) # 열 합 배열

array([16, 30])

In [70]:
a.sum(axis=1) # 행 합 배열

array([30, 13,  3])

In [71]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [81]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [82]:
# 일차원으로 펼쳐서 계산, 누적합 cumulate
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [84]:
a.cumsum(axis=0)  # 시험예상, 행을 따라 세로 합산

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [85]:
a.cumsum(axis=1) # 시험예상, 행을 따라 가로 합산

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [86]:
import numpy as np
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [87]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [88]:
np.add(a, b)

array([ 3,  6, 11])

In [89]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [90]:
np.power(a, b)

array([ 1, 16, 81])

## 배열 슬라이싱과 형태 수정

In [92]:
import numpy as np
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [93]:
print(a[3])
print(a[-2])

9
64


In [94]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [96]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [97]:
a[::-2]

array([81, 49, 25,  9,  1])

In [98]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [100]:
a[2:5] = [-5, -5, -5] #  대입될 원소 수가 2개 이상일 경우 대입 수를 매치시켜야함
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [103]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

### 2차원 배열

In [104]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [105]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [107]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [108]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [109]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [110]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [111]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [112]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [113]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

### 3차원 배열

In [115]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [116]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [117]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [118]:
a[:, 1, 1]

array([ 5, 17])

In [119]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [120]:
a[..., 1] # a[:, :, 1]과 동일

array([[ 1,  5,  9],
       [13, 17, 21]])

In [121]:
a[1, ..., 1]

array([13, 17, 21])

In [122]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
a[0]  # a[0, ...] == a[0, :, :]과 동일

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [125]:
b = a.ravel() # 1차원 배열로 만드는 ndarray.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### np.transpose(a)와 a.transpose(), a.T 전치행렬

In [126]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [128]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [129]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [130]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [131]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [132]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [133]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [134]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [147]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [148]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [149]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [150]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [151]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [152]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [153]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [155]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [156]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [157]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [158]:
org

array([  0,   1, 200,   3,   4])

In [160]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [161]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [162]:
org

array([0, 1, 2, 3, 4])

In [164]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [166]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [167]:
print(x.base)

None


In [168]:
y.base

array([0, 1, 2, 3, 4, 5])

In [169]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [171]:
c = z.copy()
print(c.base)

None


In [172]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [173]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [174]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [177]:
# 원소가 개인 배열 부분에 3개의 원소를 삽입 불가능

## 브로드캐스팅

In [178]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a+b

array([11, 11, 11])

In [179]:
# 원소 3개를 4개와 맞출 수 없어 브로드캐스팅 수행 불가
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [181]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [183]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [184]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [185]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [187]:
np.set_printoptions(precision=2)

In [188]:
x/y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [189]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [190]:
from numpy import arange
x = arange(1, 4)
x

array([1, 2, 3])

In [191]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [192]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [193]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [194]:
from numpy import arange
x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [195]:
y = arange(1, 3)
y

array([1, 2])

In [196]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [197]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [199]:
import numpy as np
from numpy import array
x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [200]:
np.newaxis is None

True

In [201]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [202]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [203]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [204]:
a.shape

(4, 1)

In [205]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [206]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [207]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [208]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [209]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [212]:
print(x[2])
print(x[[2, 3]])

2
[2 3]


In [213]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [214]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

### 2차원 배열의 색인

In [224]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [222]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [225]:
x[0, 1]

np.int64(1)

In [226]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [227]:
x[0, 2:8]

array([2, 3, 4, 5, 6, 7])

In [228]:
x[[0], [1]]

array([1])

In [229]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [230]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [231]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [232]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [233]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [236]:
x[[1, 3], [2, 2]] # 참조하는 축의 배열구조가 동일해야 하며 다르면 브로드캐스팅이 가능해야함


array([10, 26])

In [237]:
x[[1, 3], [2]]  # 브로드캐스팅

array([10, 26])

In [238]:
x[[1, 3], 2]

array([10, 26])

In [239]:
from numpy import arange

x  = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [240]:
x[np.array([0, 2, 4]), 1] # 1축의 1이 브로드캐스팅->[1, 1, 1]이 되어 각각 대응되는 순서대로
                          # 점자 [0, 1] [2, 1] [4, 1]에 해당하는 [1, 17, 33]으로 구성

array([ 1, 17, 33])

In [243]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [244]:
x[array([0, 2, 4]), 2]

array([ 2, 18, 34])

### 기본, 고급 색인 방법


In [246]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [247]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [248]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [250]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [251]:
a[arange(2, 4)][:, [1,0]]

array([[17, 16],
       [25, 24]])

In [252]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [253]:
a[arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [261]:
a[arange(2, 5)][:, arange(-1, -8, -1)] # 행 2-4까지, 열 -1에서 -7까지 선택

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])