<a href="https://colab.research.google.com/github/revivalroot/2026-BDA/blob/main/code/04w-array-stack-split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4주차 배열

## 1. 배열 결합

In [1]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [2]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
np.vstack((a, b))   # 수직 결합

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y)) # 1차원 길이가 같아야함

array([[1, 2, 3],
       [5, 6, 7]])

In [5]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [8]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [9]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [10]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [11]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [12]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [13]:
np.column_stack == np.hstack

False

In [14]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [16]:
np.row_stack((a, b))  # np.vstack()과 동일

/tmp/ipykernel_1087/3557203011.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))  # np.vstack()과 동일


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [17]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [18]:
np.concatenate((a, b, c)) # 기본적으로 축 0을 중심으로 합치는 기능 axis=0

array([1, 2, 3, 4, 5, 6])

In [19]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [20]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [21]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [23]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [24]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [25]:
np.concatenate((x, y), axis=1)  # hstack(), column_stack()과 같은 기능 수행

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [26]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [27]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [28]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
np.stack((a, b), axis=-1) # 위와 동일

array([[1, 4],
       [2, 5],
       [3, 6]])

### 3차원 배열 이해

In [31]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [33]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [34]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [35]:
ax0.shape # 2행 3열의 2차원 배열 3개 -> 3차원

(3, 2, 3)

In [36]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [37]:
ax1.shape

(2, 3, 3)

In [38]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [39]:
ax2.shape

(2, 3, 3)

In [40]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [41]:
x # (2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
x[:, :, np.newaxis] # 축을 하나 추가 -> (2, 3, 1)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [43]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [44]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [45]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [46]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [47]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [48]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [49]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [50]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [51]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [53]:
np.row_stack((a, b))

/tmp/ipykernel_1087/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [54]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

#### np.c_[]

In [55]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [56]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [59]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [60]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [61]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [62]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

#### np.r_[]

In [63]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [64]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [65]:
np.row_stack((a, b))

/tmp/ipykernel_1087/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [67]:
np.r_[3:10:3, [0]*2,  5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [68]:
np.r_[-1:1:6j, [0]*2,  5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [69]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [70]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [72]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [73]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [74]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [75]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [76]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]] # 0축으로 최소 2차원 배열

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [78]:
# 배열 차수의 증가
arr = np.array([1, 2, 3])
print(arr[np.newaxis, :])
print(arr[np.newaxis, :].shape, '\n')
print(arr[:, np.newaxis])
print(arr[:, np.newaxis].shape)

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1)


In [79]:
np.r_[[1, 2, 3], [4, 5, 6]]

array([1, 2, 3, 4, 5, 6])

In [80]:
np.r_['0, 2, 0', [1, 2, 3], [4, 5, 6]]  # 축 0으로 최소 2차원 (3, 1)로 확장

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [81]:
np.r_['1, 2, 0', [1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [82]:
np.r_['0, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.r_['1, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3, 4, 5, 6]])

In [84]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [85]:
print(np.expand_dims(a, axis=(0, 1)))
print(np.expand_dims(a, axis=(0, 1)).shape)

[[[1 2 3]]]
(1, 1, 3)


In [86]:
print(np.expand_dims(a, axis=(0, 2)))
print(np.expand_dims(a, axis=(0, 2)).shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [87]:
print(np.expand_dims(a, axis=(1, 2)))
print(np.expand_dims(a, axis=(1, 2)).shape)

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)


In [88]:
np.expand_dims(np.array([1, 2, 3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [89]:
np.expand_dims(np.array([4, 5, 6]), axis=(1, 2))

array([[[4]],

       [[5]],

       [[6]]])

In [90]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [91]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape

(6, 1, 1)

In [92]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [93]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 2)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [94]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [95]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [96]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 1)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [97]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]].shape

(2, 1, 3)

In [98]:
import numpy as np
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [99]:
type(a)

numpy.matrix

In [100]:
b = np.matrix([[1, 3], [3, 2]])
b

matrix([[1, 3],
        [3, 2]])

In [101]:
a * b

matrix([[ 7,  7],
        [15, 17]])

In [102]:
a @ b

matrix([[ 7,  7],
        [15, 17]])

In [103]:
print(np.r_[[[1, 2, 3]], [[4, 5, 6]]])

# 2차원 매트릭스 생성
np.r_['r', [[1, 2, 3], [4, 5, 6]]]

[[1 2 3]
 [4 5 6]]


matrix([[1, 2, 3],
        [4, 5, 6]])

In [104]:
np.r_['c', [[1, 2, 3]], [[4, 5, 6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [105]:
print(np.r_[[1,2,3], [4, 5, 6]])

np.r_['r', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [106]:
print(np.r_[[1,2,3], [4, 5, 6]])

np.r_['c', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

### 1차원 배열 다양한 방향으로 쌓기

In [107]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [108]:
# 수평 방향으로 쌓기
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [109]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [110]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [111]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [112]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [113]:
# 수직 방향으로 쌓기
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.row_stack((a, b))

/tmp/ipykernel_1087/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [118]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [119]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [121]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## 2.배열 분리

In [122]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [123]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [124]:
import numpy as np

y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [125]:
np.split(y, [2, 3, 4, 6]) # 0~1, 2, 3~4, 5->인덱스

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [126]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [128]:
a = np.arange(24).reshape(2, 12)

In [129]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [130]:
np.split(a, 3, axis=1)  # 배열 a를 축 1방향으로 12/3 = 4

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [131]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [132]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [133]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [134]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [135]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [136]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [137]:
a = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [139]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [141]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [142]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [143]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [144]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [145]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [146]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [147]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [148]:
# np.vsplit(a, 4) -> 분리 수 4개 나누어 지지 않아 오류

In [149]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [150]:
a[:1, :]

array([[0, 1, 2]])

In [151]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [152]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [153]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [154]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [155]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [156]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [157]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [158]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [159]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [160]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [161]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [162]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [163]:
np.array_split(x, 2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [164]:
import numpy as np

np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [165]:
np.array_split(x, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [166]:
np.array_split(x, 5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [167]:
np.array_split(x, [2, 4, 8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

In [168]:
import numpy as np

a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [169]:
np.array_split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [170]:
np.array_split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [171]:
import numpy as np

a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [172]:
np.array_split(a, [2, 4], axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [173]:
np.array_split(a, [2, 4], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [174]:
import numpy as np

x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [175]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [176]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [177]:
np.split(x, 2)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])]

In [178]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [179]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [180]:
np.dsplit(x, [2, 4, 5]) # n:등분이 안되면 오류

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

## 3. numpy의 난수와 다양한 함수

### 난수 기초와 생성

In [181]:
import numpy as np

rg = np.random.default_rng(12345) # rng: 난수 생성기, 인자12345는 비트제네레이터를 초기화하는 시드 값
rg

Generator(PCG64) at 0x7F53AFC4C740

In [182]:
r = rg.random() # [0, 1) 실수 난수
r

0.22733602246716966

In [183]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [184]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [185]:
import numpy as np

rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [186]:
rg.integers(1, 7, (3, 4)) # 3행 4열에서 랜덤한 수 1~6까지가 들어감

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [187]:
import numpy as np

# 정규 분포 난수 10개
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [188]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])

### Numpy 스택 함수 비교: vstack/hstack/row_stack/column_stacl

In [192]:
a = np.arange(1, 4)
b = np.arange(4, 7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [191]:
x = np.arange(1, 7).reshape(2, 3)
y = np.arange(7, 13).reshape(2, 3)
x, y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [193]:
np.vstack((a, b)) # 1D->2D

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [195]:
np.vstack((x, y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [197]:
np.hstack((x, y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [198]:
np.column_stack((a, b)) # 1D->2D

array([[1, 4],
       [2, 5],
       [3, 6]])

In [200]:
np.column_stack((a, b)), np.c_[a, b] # 1D -> 2D

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [201]:
np.column_stack((x, y)), np.c_[x, y] # 1D -> 2D

(array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))

In [206]:
m = np.arange(24).reshape(2, 3, 4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [210]:
n = np.arange(96).reshape(4, 4, 6)
n

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [216]:
np.split(n, 2)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],
 
        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]]]),
 array([[[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]],
 
        [[72, 73, 74, 75, 76, 77],
         [78, 79, 80, 81, 82, 83],
         [84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95]]])]

In [219]:
np.split(n, 2)[1]

array([[[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [220]:
np.split(n, 2)[1].shape

(2, 4, 6)

In [221]:
np.split(n, 2, axis=1)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],
 
        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]],
 
        [[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59]],
 
        [[72, 73, 74, 75, 76, 77],
         [78, 79, 80, 81, 82, 83]]]),
 array([[[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],
 
        [[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]],
 
        [[60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]],
 
        [[84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95]]])]

In [222]:
np.split(n, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14],
         [18, 19, 20]],
 
        [[24, 25, 26],
         [30, 31, 32],
         [36, 37, 38],
         [42, 43, 44]],
 
        [[48, 49, 50],
         [54, 55, 56],
         [60, 61, 62],
         [66, 67, 68]],
 
        [[72, 73, 74],
         [78, 79, 80],
         [84, 85, 86],
         [90, 91, 92]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17],
         [21, 22, 23]],
 
        [[27, 28, 29],
         [33, 34, 35],
         [39, 40, 41],
         [45, 46, 47]],
 
        [[51, 52, 53],
         [57, 58, 59],
         [63, 64, 65],
         [69, 70, 71]],
 
        [[75, 76, 77],
         [81, 82, 83],
         [87, 88, 89],
         [93, 94, 95]]])]