<a href="https://colab.research.google.com/github/revivalroot/2026-BDA/blob/main/code/04w.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4주차 배열

### 배열 결합

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a, b))   # 수직 결합

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y)) # 1차원 길이가 같아야함

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.column_stack == np.hstack

False

In [ ]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a, b))  # np.vstack()과 동일

/tmp/ipykernel_336/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [ ]:
np.concatenate((a, b, c)) # 기본적으로 축 0을 중심으로 합치는 기능 axis=0

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate((x, y), axis=1)  # hstack(), column_stack()과 같은 기능 수행

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a, b), axis=-1) # 위와 동일

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [ ]:
ax0.shape # 2행 3열의 2차원 배열 3개 -> 3차원

(3, 2, 3)

In [ ]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [ ]:
ax1.shape

(2, 3, 3)

In [ ]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
ax2.shape

(2, 3, 3)

In [ ]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [ ]:
x # (2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x[:, :, np.newaxis] # 축을 하나 추가 -> (2, 3, 1)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [ ]:
np.row_stack((a, b))

/tmp/ipykernel_336/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [ ]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.row_stack((a, b))

/tmp/ipykernel_336/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [ ]:
np.r_[3:10:3, [0]*2,  5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [ ]:
np.r_[-1:1:6j, [0]*2,  5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [ ]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]] # 0축으로 최소 2차원 배열

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
# 배열 차수의 증가
arr = np.array([1, 2, 3])
print(arr[np.newaxis, :])
print(arr[np.newaxis, :].shape, '\n')
print(arr[:, np.newaxis])
print(arr[:, np.newaxis].shape)

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1)


In [ ]:
np.r_[[1, 2, 3], [4, 5, 6]]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.r_['0, 2, 0', [1, 2, 3], [4, 5, 6]]  # 축 0으로 최소 2차원 (3, 1)로 확장

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.r_['1, 2, 0', [1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.r_['0, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_['1, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [ ]:
print(np.expand_dims(a, axis=(0, 1)))
print(np.expand_dims(a, axis=(0, 1)).shape)

[[[1 2 3]]]
(1, 1, 3)


In [ ]:
print(np.expand_dims(a, axis=(0, 2)))
print(np.expand_dims(a, axis=(0, 2)).shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [ ]:
print(np.expand_dims(a, axis=(1, 2)))
print(np.expand_dims(a, axis=(1, 2)).shape)

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)


In [ ]:
np.expand_dims(np.array([1, 2, 3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [ ]:
np.expand_dims(np.array([4, 5, 6]), axis=(1, 2))

array([[[4]],

       [[5]],

       [[6]]])

In [ ]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [ ]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape

(6, 1, 1)

In [ ]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 2)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [ ]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [ ]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 1)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [ ]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]].shape

(2, 1, 3)

In [ ]:
import numpy as np
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(a)

numpy.matrix

In [ ]:
b = np.matrix([[1, 3], [3, 2]])
b

matrix([[1, 3],
        [3, 2]])

In [ ]:
a * b

matrix([[ 7,  7],
        [15, 17]])

In [ ]:
a @ b

matrix([[ 7,  7],
        [15, 17]])

In [ ]:
print(np.r_[[[1, 2, 3]], [[4, 5, 6]]])

# 2차원 매트릭스 생성
np.r_['r', [[1, 2, 3], [4, 5, 6]]]

[[1 2 3]
 [4 5 6]]


matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
np.r_['c', [[1, 2, 3]], [[4, 5, 6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print(np.r_[[1,2,3], [4, 5, 6]])

np.r_['r', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [ ]:
print(np.r_[[1,2,3], [4, 5, 6]])

np.r_['c', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

### 1차원 배열 다양한 방향으로 쌓기

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
# 수평 방향으로 쌓기
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
# 수직 방향으로 쌓기
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.row_stack((a, b))

/tmp/ipykernel_336/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열 분리

In [ ]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
import numpy as np

y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.split(y, [2, 3, 4, 6]) # 0~1, 2, 3~4, 5->인덱스

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [ ]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [ ]:
a = np.arange(24).reshape(2, 12)

In [ ]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a, 3, axis=1)  # 배열 a를 축 1방향으로 12/3 = 4

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [ ]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [ ]:
a = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [ ]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [ ]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
# np.vsplit(a, 4) -> 분리 수 4개 나누어 지지 않아 오류

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [ ]:
a[:1, :]

array([[0, 1, 2]])

In [ ]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [ ]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [ ]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [ ]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [ ]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [ ]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
np.array_split(x, 2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [ ]:
import numpy as np

np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
np.array_split(x, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [ ]:
np.array_split(x, 5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [ ]:
np.array_split(x, [2, 4, 8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

In [ ]:
import numpy as np

a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [ ]:
np.array_split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [ ]:
np.array_split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [ ]:
import numpy as np

a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [ ]:
np.array_split(a, [2, 4], axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [ ]:
np.array_split(a, [2, 4], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [ ]:
import numpy as np

x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [ ]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
np.split(x, 2)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])]

In [ ]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [ ]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
np.dsplit(x, [2, 4, 5]) # n:등분이 안되면 오류

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

## numpy의 난수와 다양한 함수

In [ ]:
import numpy as np

rg = np.random.default_rng(12345) # rng: 난수 생성기, 인자12345는 비트제네레이터를 초기화하는 시드 값
rg

Generator(PCG64) at 0x7A592467BD80

In [ ]:
r = rg.random() # [0, 1) 실수 난수
r

0.22733602246716966

In [ ]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [ ]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [ ]:
import numpy as np

rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [ ]:
rg.integers(1, 7, (3, 4)) # 3행 4열에서 랜덤한 수 1~6까지가 들어감

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [ ]:
import numpy as np

# 정규 분포 난수 10개
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [ ]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])